name: Deploy Net6 DEV
on:
  push:
    branches: ["dev"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  Deploy:
    permissions:
      contents: read
      security-events: write
    uses: bci-seguros/devops/.github/workflows/wkfl_dev_net6.yml@main    
    with:          
      activar_sonar_dev: no
      activar_dependency_dev: no
      config_parametros: >
           
    secrets:
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      KEY_SERVER_IIS: ${{ secrets.KEY_DEPLOY_DEV }}
      CONFIG_CONNECTIONSTRINGS: >
